### ISSUE TITLE
add "review" functionality to upload_metadata command

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans-api#73]
## Task checklist

- [ ] **Add a boolean `click` option for `upload_metadata_cli` in `command_line.py`**
The function should require either this or `create_csv` to be true, but not both.
- [ ] **Create a `review_metadata_csv` function in `utils_fs.py`**
Check for CSV format and that header and rows correspond to what `mk_metadata_csv` produces and `load_metadata_csv` uses.
- [ ] **Modify `upload_metadata` to run `review_metadata_csv`**
Run this on the file specified by `output_csv` if the `review` parameter is true.

## Description
Open Humans requires metadata for uploaded files. To satisfy this, running an upload via the command line requires the use of an additional metadata file.

Currently, the command line can be used to generate a minimal metadata file, but it can't be used to review that an existing one is valid. The `upload_metadata_cli` and `upload_metadata` commands in `ohapi/command_line.py` currently accept a `review` parameter that isn't implemented.

We would like this `review` parameter to be implemented, adding functionality to review that an existing CSV metadata file is formatted correctly.

**Comment by DartingMelody** [comment]
Looks great! I'd like to start working on it! :)
